# Welcome to Jekyll!

title: Mathematical and Computational Biology In Drug Discovery
email: jitao-david.zhang@unibas.ch
description: >- # this means to ignore newlines until "baseurl:"
  University of Basel/ Spring Semester 2023/ Fridays 12:15-14:00

theme: jekyll-theme-slate
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
