all: causal-chain.pdf causal-chain-expanded.pdf

causal-chain.pdf: causal-chain.gv
	dot causal-chain.gv -Tpdf -o causal-chain.pdf

causal-chain-expanded.pdf: causal-chain-expanded.gv
	dot causal-chain-expanded.gv -Tpdf -o causal-chain-expanded.pdf
