---
title: "2021-06-combining-models.Rmd"
author: "Jitao david Zhang"
date: "14/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.height=4.5, fig.width=4.5)
library(ribiosPlot)
```

## A mixture of models

```{r}
set.seed(1887)
mcauchy <- c(rcauchy(100),
             rcauchy(100, 3, 1),
             rcauchy(100, 5, 1))
myd <- sample(mcauchy, 10)
scaledDensity <- function(x, scaleFactor=1, ...) {
  res <- density(x, ...)
  res$y <- res$y * scaleFactor
  return(res)
}
{
  compactPar()
  plot(density(mcauchy), xlim=c(-15,15),
       main="A mixture of Cauchy distributions", xlab="data")
  rug(myd, ticksize = 0.1, lwd = 2, col="magenta")
  lines(scaledDensity(mcauchy[1:100], 1/3), col="red", lty=2)
  lines(scaledDensity(mcauchy[101:200], 1/3), col="yellow3", lty=2)
  lines(scaledDensity(mcauchy[201:300], 1/3), col="navyblue", lty=2)
  abline(v=0, h=0)
}
```

```{r}
mnorm <- c(rnorm(100),
             rnorm(100, 3, 1),
             rnorm(100, 5, 1))
{
  compactPar()
  plot(density(mnorm), xlim=c(-15,15),
       main="A mixture of Normal distributions", xlab="")
  rug(myd, ticksize = 0.1, lwd = 2, col="magenta")
  lines(scaledDensity(mnorm[1:100], 1/3), col="red", lty=2)
  lines(scaledDensity(mnorm[101:200], 1/3), col="yellow3", lty=2)
  lines(scaledDensity(mnorm[201:300], 1/3), col="navyblue", lty=2)
  abline(v=0, h=0)
}
```